name: my_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  device_info: ^0.4.2+1
  package_info: ^0.4.0+17
  cupertino_icons: ^0.1.3
  flutter_icons: ^1.1.0

  provider: ^4.1.1
  connectivity: ^0.4.8+5
  shared_preferences: ^0.5.7+1
  http: ^0.12.1
  webview_flutter: ^0.3.21
  intl: ^0.16.0
  flutter_html: ^0.11.0
  url_launcher: ^5.4.5
  shimmer: ^1.1.1
  animations: ^1.0.0+5
#  firebase_analytics: ^5.0.1

  cached_network_image: ^2.1.0+1
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/locale/
    - assets/images/ui/
    # Locale
    - assets/locale/en/
    - assets/locale/vi/

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.io/custom-fonts/#from-packages