name: my_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^7.2.0
  logger: ^1.1.0
  fluttertoast: ^8.0.8
  http: ^0.13.3
  device_info_plus: ^2.1.0
  package_info_plus: ^1.0.6
  shared_preferences: ^2.0.6
  get_it: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/images/
    - assets/images/locale/
